# Generated by Django 5.0.6 on 2024-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0002_alter_interview_online_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_task_answer_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='online_meet_link',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
