# Generated by Django 5.0.6 on 2024-06-22 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0002_job_application_shortlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='is_accepted',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='Accepted_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.job_application')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.employer')),
            ],
        ),
    ]
