# Generated by Django 5.0.6 on 2024-06-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0003_job_application_is_accepted_accepted_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepted_application',
            old_name='Job_application',
            new_name='job_application',
        ),
    ]
