# Generated by Django 5.0.6 on 2024-06-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0003_job_seeker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_seeker',
            new_name='Jobseeker',
        ),
    ]
