# Generated by Django 5.0.6 on 2024-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0003_alter_interview_interview_task_answer_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='online_meet_link',
            field=models.CharField(max_length=250),
        ),
    ]
