# Generated by Django 5.0.6 on 2024-06-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0004_rename_job_application_accepted_application_job_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accepted_application',
        ),
    ]
