# Generated by Django 5.0.6 on 2024-06-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0004_alter_interview_online_meet_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hire',
            old_name='mail',
            new_name='message',
        ),
    ]
