# Generated by Django 5.0.6 on 2024-06-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0004_rename_job_seeker_jobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='profile_picture',
            field=models.FileField(upload_to='my_files'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('subject', models.CharField(max_length=250)),
                ('feedback', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_jobseeker', to='job_portal_app.jobseeker')),
            ],
        ),
    ]
