# Generated by Django 5.0.6 on 2024-06-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0005_delete_accepted_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application',
            old_name='is_accepted',
            new_name='is_shortlisted',
        ),
    ]
