# Generated by Django 5.0.6 on 2024-06-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0006_rename_is_accepted_job_application_is_shortlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.employer')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.job_application')),
            ],
        ),
    ]
