# Generated by Django 5.0.6 on 2024-06-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0007_shortlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application',
            name='shortlist_status',
        ),
    ]
