# Generated by Django 5.0.6 on 2024-06-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0007_rename_application_deadline_job_post_application_last_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_post',
            old_name='ressuma',
            new_name='image',
        ),
    ]
