# Generated by Django 5.0.6 on 2024-06-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0008_rename_ressuma_job_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_post',
        ),
    ]
