# Generated by Django 5.0.6 on 2024-06-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0009_delete_job_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='my_files')),
                ('job_role', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('application_last_date', models.DateField()),
                ('posted_date', models.DateField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_jobseeker', to='job_portal_app.employer')),
            ],
        ),
    ]
