# Generated by Django 5.0.6 on 2024-06-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0009_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='date',
            new_name='interview_date',
        ),
        migrations.AddField(
            model_name='shortlist',
            name='is_interview_created',
            field=models.BooleanField(default=0),
        ),
    ]
