# Generated by Django 5.0.6 on 2024-06-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0010_job_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='job_role',
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_roles',
            field=models.CharField(default='hii', max_length=500),
        ),
    ]
