# Generated by Django 5.0.6 on 2024-06-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0012_alter_job_post_job_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_post',
            old_name='qualification',
            new_name='educational_qualification',
        ),
    ]
