# Generated by Django 5.0.6 on 2024-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0015_jobseeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='my_files'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='my_files'),
        ),
    ]
