# Generated by Django 5.0.6 on 2024-06-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0016_alter_employer_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_job_post', to='job_portal_app.job_post')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_jobseeker', to='job_portal_app.jobseeker')),
            ],
        ),
    ]
