# Generated by Django 5.0.6 on 2024-06-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0017_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='apply_status',
            field=models.BooleanField(default=False),
        ),
    ]
